CREATE DATABASE MoMo;
USE MoMo;

-- USERS
CREATE TABLE USERS (
    user_id VARCHAR(20) PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SYSTEM LOGS (RAW SMS)
CREATE TABLE SYSTEM_LOGS (
    log_id VARCHAR(20) PRIMARY KEY,
    raw_body TEXT NOT NULL,
    received_at DATETIME NOT NULL,
    processed_status ENUM('PENDING','PROCESSED','FAILED') DEFAULT 'PENDING'
);

-- TRANSACTIONS
CREATE TABLE TRANSACTIONS (
    transaction_id VARCHAR(20) PRIMARY KEY,
    amount DECIMAL(12,2) NOT NULL CHECK (amount > 0),
    fee DECIMAL(10,2) DEFAULT 0 CHECK (fee >= 0),
    balance_after DECIMAL(12,2),
    transaction_datetime DATETIME NOT NULL,
    status ENUM('COMPLETED','FAILED','PENDING'),
    log_id VARCHAR(20) UNIQUE,
    FOREIGN KEY (log_id) REFERENCES SYSTEM_LOGS(log_id)
);

-- TRANSACTION CATEGORY
CREATE TABLE TRANSACTION_CATEGORY (
    category_id VARCHAR(20) PRIMARY KEY,
    category_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

-- M:N TRANSACTION CATEGORY
CREATE TABLE TRANSACTION_CATEGORY_MAP (
    transaction_id VARCHAR(20),
    category_id VARCHAR(20),
    PRIMARY KEY (transaction_id, category_id),
    FOREIGN KEY (transaction_id) REFERENCES TRANSACTIONS(transaction_id),
    FOREIGN KEY (category_id) REFERENCES TRANSACTION_CATEGORY(category_id)
);

-- TRANSACTION PARTICIPANTS
CREATE TABLE TRANSACTION_PARTICIPANTS (
    participant_id VARCHAR(20) PRIMARY KEY,
    transaction_id VARCHAR(20),
    user_id VARCHAR(20),
    role ENUM('SENDER','RECEIVER') NOT NULL,
    FOREIGN KEY (transaction_id) REFERENCES TRANSACTIONS(transaction_id),
    FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

-- INDEXES
CREATE INDEX idx_tx_date ON TRANSACTIONS(transaction_datetime);
CREATE INDEX idx_tx_status ON TRANSACTIONS(status)
